# Text Similarity - Levenshtein Distance

For the purposes of this tutorial I will show you the code necessary to implement Levenshtein distance in Python but for the actual text similarity pipeline we will be using the Levenshtein-python package. You can look through the installation guidelines [here](https://pypi.org/project/python-Levenshtein/) or run the following command:   
```console
pip install python-Levenshtein  
```  

### Introduction to Text Similarity
Identifying similarity between text is a common problem in NLP and is used by many companies world wide. The most common application of text similarity comes from the form of identifying plagiarized text. Educational facilities ranging from elementary school, high school, college and universities all around the world use services like Turnitin to ensure the work submitted by students is original and their own. Other applications of text similarity is commonly used by companies which have a similar structure to Stack Overflow or Stack Exchange. They want to be able to identify and flag duplicated questions so the user posting the question can be referenced to the original post with the solution. This increases the number of unique questions being asked on their platform.  

Text similarity can be broken down into two components, semantic similarity and lexical similarity. Given a pair of text, the semantic similarity of the pair refers to how close the documents are in meaning. Whereas, lexical similarity is a measure of overlap in vocabulary. If both documents in the pairs have the same vocabularies, then they would have a lexical similarity of 1 and vice versa of 0 if there was no overlap in vocabularies [2].    

Achieving true semantic similarity is a very difficult and unsolved task in both NLP and Mathematics. It's a heavily researched area and a lot of the solutions proposed does involve a certain degree of lexical similarity in them. For the focuses of this article, I will not dive much deeper into semantic similarity, but focus a lot more on lexical similarity.  

### Levenshtein Distance  
There are many ways to identify the lexical similarities between a pair of text, the one which we'll be covering today in this article is Levenshtein distance. An algorithm invented in 1965 by Vladimir Levenshtein, a Soviet mathematician [1].  
### Intuition  
>Levenshtein distance is very impactful because it does not require two strings to be of equal length for them to be compared. >Intuitively speaking, Levenshtein distance is quite easy to understand.  
>Informally, the Levenshtein distance between two words is the minimum number of single-character edits (insertions, deletions or substitutions) required to change one word into the other. [1]  
>- https://en.wikipedia.org/wiki/Levenshtein_distance  

Essentially implying that the output distance between the two is the cumulative sum of the single-character edits. The larger the output distance is implies that more changes were necessary to make the two words equal each other, and the lower the output distance is implies that fewer changes were necessary. For example, given a pair of words dream and dream the resulting Levenshtein distance would be 0 because the two words are the same. However, if the words were dream and steam the Levenshtein distance would be 2 as you would need to make 2 edits to change dr to st .
Thus a large value for Levenshtein distance implies that the two documents were not similar, and a small value for the distance implies that the two documents were similar.

## Implement Levenshtein Distance

The Python code associated to implementing  Levenshtein distance using dynamic programming. The same code can be implemented through a brute force and iterative solution (be aware that the brute force solution would not be optimal in terms of time complexity).  

In [1]:
from functools import lru_cache

In [2]:
def lev_dist(a, b):
    '''
    This function will calculate the levenshtein distance between two input
    strings a and b
    
    params:
        a (String) : The first string you want to compare
        b (String) : The second string you want to compare
        
    returns:
        This function will return the distnace between string a and b.
        
    example:
        a = 'stamp'
        b = 'stomp'
        lev_dist(a,b)
        >> 1.0
    '''
    
    @lru_cache(None)  # for memorization
    def min_dist(s1, s2):

        if s1 == len(a) or s2 == len(b):
            return len(a) - s1 + len(b) - s2

        # no change required
        if a[s1] == b[s2]:
            return min_dist(s1 + 1, s2 + 1)

        return 1 + min(
            min_dist(s1, s2 + 1),      # insert character
            min_dist(s1 + 1, s2),      # delete character
            min_dist(s1 + 1, s2 + 1),  # replace character
        )

    return min_dist(0, 0)

In [3]:
sq1 = 'saturday'
sq2 = 'sunday'
lev_dist(sq1, sq2)

3

For the purpose of comparing the user input article to another article, we will reference Wikipedia. You are able to fetch Wikipedia text data very easily through the Wikipedia library. You can run the following command on your console :   
```pip3 install wikipedia```  
or reference the installation documentation for this library [here](https://pypi.org/project/Wikipedia-API/).

## Text Similarity

In [10]:
import string
import Levenshtein as lev
import wikipedia

from nltk.corpus import stopwords

### Problem Statement 
Similar to softwares like Turnitin, we want to build a pipeline which identifies if an input article is plagiarized.   

### Solution Architecture
To solve this problem a few things will be required. Firstly, we need to get the information passed on by the user of the pipeline, for this we not only require the article that they want to check the plagiarism against but also a keyword tag which corresponds to that article. For the simplicity of this tutorial, we'll used the initial text I've written for this article with the tag being `Levenshtein Distance`. Second, we need a large corpus of documents we want to compare the user input text with. We can leverage the Wikipedia-API to get access to Wikipedia articles associated to the tag of the user input data.  We can then clean the user input document for redundancies like stopwords and punctuations to better optimize the calculation of Levenshtein distance. We pass this cleaned document through each document in our corpus under the same tag as the user input document and identify if there is any document which is very similar to the user submitted document.   

## Fetch Data

In [5]:
user_article = '''
Identifying similarity between text is a common problem in NLP and is used by many companies world wide. The most common application of text similarity comes from the form of identifying plagiarized text. Educational facilities ranging from elementary school, high school, college and universities all around the world use services like Turnitin to ensure the work submitted by students is original and their own. Other applications of text similarity is commonly used by companies which have a similar structure to Stack Overflow or Stack Exchange. They want to be able to identify and flag duplicated questions so the user posting the question can be referenced to the original post with the solution. This increases the number of unique questions being asked on their platform. 
Text similarity can be broken down into two components, semantic similarity and lexical similarity. Given a pair of text, the semantic similarity of the pair refers to how close the documents are in meaning. Whereas, lexical similarity is a measure of overlap in vocabulary. If both documents in the pairs have the same vocabularies, then they would have a lexical similarity of 1 and vice versa of 0 if there was no overlap in vocabularies [2].
Achieving true semantic similarity is a very difficult and unsolved task in both NLP and Mathematics. It's a heavily researched area and a lot of the solutions proposed does involve a certain degree of lexical similarity in them. For the focuses of this article, I will not dive much deeper into semantic similarity, but focus a lot more on lexical similarity.
Levenshtein Distance
There are many ways to identify the lexical similarities between a pair of text, the one which we'll be covering today in this article is Levenshtein distance. An algorithm invented in 1965 by Vladimir Levenshtein, a Soviet mathematician [1].
Intuition
Levenshtein distance is very impactful because it does not require two strings to be of equal length for them to be compared. Intuitively speaking, Levenshtein distance is quite easy to understand.
Informally, the Levenshtein distance between two words is the minimum number of single-character edits (insertions, deletions or substitutions) required to change one word into the other. [1]
- https://en.wikipedia.org/wiki/Levenshtein_distance
Essentially implying that the output distance between the two is the cumulative sum of the single-character edits. The larger the output distance is implies that more changes were necessary to make the two words equal each other, and the lower the output distance is implies that fewer changes were necessary. For example, given a pair of words dream and dream the resulting Levenshtein distance would be 0 because the two words are the same. However, if the words were dream and steam the Levenshtein distance would be 2 as you would need to make 2 edits to change dr to st .
Thus a large value for Levenshtein distance implies that the two documents were not similar, and a small value for the distance implies that the two documents were similar.
'''

tags = ['Levenshtein distance']

In [6]:
def fetch_wiki_data(tags):
    '''
    The purpose of this function is to get the wikipedia data associated to a certain user
    input tag.
    
    params:
        tag (String) : The item you want to seach wikipedia for
        
    returns:
        This function will return the contents associated to the user specified tag
    
    example:
        tag = 'Levenshtein distance'
        fetch_wiki_data(tag)
        >> In information theory, linguistics, and computer science, the Levenshtein distance 
           is a string metric...
    '''
    content = {}
    for tag in tags:
        # get wikipedia data for the tag
        wiki_tag = wikipedia.search(tag)

        # get page info
        page = wikipedia.page(wiki_tag[0])

        # get page content
        content[tag] = page.content
    return content

In [7]:
%time tag_content = fetch_wiki_data(tags)

CPU times: user 201 ms, sys: 44.5 ms, total: 245 ms
Wall time: 3.76 s


## Clean Data

In [12]:
def remove_punctuations(txt, punct = string.punctuation):
    '''
    This function will remove punctuations from the input text
    '''
    return ''.join([c for c in txt if c not in punct])
  
def remove_stopwords(txt, sw = list(stopwords.words('english'))):
    '''
    This function will remove the stopwords from the input txt
    '''
    return ' '.join([w for w in txt.split() if w.lower() not in sw])

def clean_text(txt):
    '''
    This function will clean the text being passed by removing specific line feed characters
    like '\n', '\r', and '\'
    '''
    
    txt = txt.replace('\n', ' ').replace('\r', ' ').replace('\'', '')
    txt = remove_punctuations(txt)
    txt = remove_stopwords(txt)
    return txt.lower()

In [13]:
%time user_article = clean_text(user_article) 

CPU times: user 4.93 ms, sys: 514 µs, total: 5.44 ms
Wall time: 6.59 ms


In [15]:
%%time
for tag, content in tag_content.items():
    tag_content[tag] = clean_text(content)

CPU times: user 8.31 ms, sys: 1.5 ms, total: 9.8 ms
Wall time: 9.96 ms


## Find Similarity

In [24]:
def similarity(user_article, tag_content):
    '''
    This function will identify the similarities between the user_article and all the
    content within tag_content
    
    params:
        user_article (String) : The text submitted by the user
        tag_content (Dictionary) : Key is the tag and the value is the content you want 
                                   to compare with the user_article
    
    returns:
        This function will return a dictionary holding the Levenshtein assocaited to the 
        user_article with each tag_content
    '''
    
    distances = {}
    for tag,content in tag_content.items():
        dist = lev.distance(user_article, content)
        distances[tag] = dist
    return distances

In [28]:
distances = similarity(user_article, tag_content)
distances

{'Levenshtein distance': 4936}

Now this value might seem relatively arbitrary to you, its hard to determine if this value reflects that the content is plagiarized or not. The larger the value is the less likely it is to be considered plagiarized based on our understanding of Levenshtein distance. However its difficult to determine that threshold of what distance is not large enough. 

## Check Plagiarism

In [35]:
def is_plagiarism(user_article, tag_content, distances, th = 0.4):
    '''
    This function will identify if the user_article is considered plagiarized for each
    of the tag_content based on the distances observed.
    
    params:
        user_article (String) : The text submitted by the user
        tag_content (Dictionary) : Key is the tag and the value is the content you want 
                                   to compare with the user_article
        distances (Dictionary) : Key is the tag and the value is the Levenshtein distance 
        th (Float) : The plagiarism threshold
    
    returns:
        A dictionary associated to the plagiarism percentage for each tag
    '''
    ua_len = len(user_article)
    distances = {tag:[d, max(ua_len, len(tag_content[tag]))] for tag,d in distances.items()}
    
    for tag, d in distances.items():
        if d[0] <= d[1] * th:
            distances[tag] = 'Plagiarized'
        else:
            distances[tag] = 'Not Plagiarized'
    return distances

In [36]:
is_plagiarism(user_article, tag_content, distances)

{'Levenshtein distance': 'Not Plagiarized'}

## Caveats
There are a number of caveats to using the pipeline outlined above. 
1) This pipeline does not identify which areas are plagiarized and which areas are not, it only yields an overall score of plagiarism.
2) The process does not account of properly cited and quoted pieces of text. This would misleadingly increase the overall plagiarism score.
3) It's difficult to determine a threshold of what how small or large a distance should be to be considered plagiarized.

## Concluding Remarks
Levenshtein distance is a lexical similarity measure which identifies the distance between one a pair of strings. It does so by counting the number of times you would have to insert, delete or substitute a character from string 1 to make it like string 2. The larger the distance between the pair implies that the strings are not similar to each other and vice versa.  
I created this pipeline in a manner such that its easily integratabtle with other text similarity measures. Levenshtein distance is a great measure to use to identify lexical similarity between a pair of text, but it does not mean there aren't other well performing similarity measures. The Jaro-Winkler score in particular comes to mind and can be easily implemented in this pipeline. Be aware that the Jaro similarity outputs a result which is interpreted differently than the Levenshtein distance.  
You can follow through with this pipeline in the Jupyter Notebook I created for this project. You can find the notebook on my GitHub page [here](https://github.com/vatsal220/medium_articles/blob/main/levenshtein_distance/lev_dist.ipynb).  

## Resources
- [1] https://en.wikipedia.org/wiki/Levenshtein_distance
- [2] https://en.wikipedia.org/wiki/Lexical_similarity
- [3] https://pypi.org/project/python-Levenshtein/
---

In [29]:
import numpy as np

def levenshtein(seq1, seq2):
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

In [39]:
a = 'stamp'
b = 'stomp'
levenshtein(a,b)

[[0. 1. 2. 3. 4. 5.]
 [1. 0. 1. 2. 3. 4.]
 [2. 1. 0. 1. 2. 3.]
 [3. 2. 1. 1. 2. 3.]
 [4. 3. 2. 2. 1. 2.]
 [5. 4. 3. 3. 2. 1.]]


1.0